### ISSUE TITLE
Missing mana-pw and mana-a symbols

### ISSUE THREAD

**Issue by crookedneighbor** [scryfall/manamoji-discord#1]
Identical to https://github.com/scryfall/manamoji-slack/issues/4

Just noticed that 2 symbols are missing:

Planeswalker:
![PW Symbol](https://img.scryfall.com/symbology/PW.svg)

Acorn:
![Acorn Symbol](https://img.scryfall.com/symbology/A.svg)

**Comment by csuhta** [comment]
Added https://github.com/scryfall/manamoji-discord/commit/926f1d95d9c55578bae59923fbe98449d1167377
