### ISSUE TITLE
SVG files available?

### ISSUE THREAD

**Issue by jimbojw** [scryfall/manamoji-discord#10]
On Scryfall, the manamojis use SVG files, rather than these PNGs. Are the SVG files made available anywhere (other than extracting them from the compiled CSS)?

I recently made a derivative project called [manamoji-css](https://github.com/jimbojw/manamoji-css) based on this project. I would have preferred to use SVG files if I could find them though.

Not a big deal, of course. The Manamojis tend to be rendered at around the size of `1em`, where the difference between 128x128 and vector graphics is beneath the level of human perception.

**Comment by csuhta** [comment]
We offer all of these files on our API: https://scryfall.com/docs/api/card-symbols
It updates live as soon as we add new symbols

**Comment by jimbojw** [comment]
I'll take a look, thanks!
