### ISSUE TITLE
Black Hybrid Symbols Have the Wrong Gray

### ISSUE THREAD

**Issue by SmashPortal** [scryfall/manamoji-discord#2]
The following files should have the same background color as `manac.png`, but instead use the darker gray only intended for `manabp.png` and  `mana2b.png`:
- `manab.png`
- `manawb.png`
- `manaub.png`
- `manab.png`
- `manabr.png`
- `manabg.png`

MTG Arena uses the darker shade for  its black mana symbols, but in paper they use the same shade as colorless mana.

**Comment by SmashPortal** [comment]
`manabp.png` also has the colorless gray when it should have the darker gray.

**Comment by SmashPortal** [comment]
`manab.png` also has the wrong (darker) shade of gray.

**Comment by csuhta** [comment]
Thanks for all of the fix reports! I've uploaded a new batch of symbols. Please let us know if you spot anything else. ❤️
